# -*- coding: utf-8 -*-
"""teste_scrapping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lGmPwBQJA5AX1ZOz4VqtMseRmsXrh3jB
"""

# Instalando e Importando bibliotecas

!pip install requests beautifulsoup4 lxml

import requests
from bs4 import BeautifulSoup
import lxml

# Obtendo os dados de uma pagina web e testando conexao

URL = "https://webscraper.io/test-sites/pagination"

res = requests.get(URL)

res.status_code

# Extraindo os dados com BeautifulSoup e mostrando titulo da pagina

soup = BeautifulSoup(res.text, "lxml")

titulo = soup.find("h1")
print("Título da página:", titulo.get_text(strip=True))

# Encontrando os cartoes de dados do site

cartoes = soup.find_all("h3")

print("Modelos encontrados:", len(cartoes))

#Extraindo os modelos de carros disponíveis

modelo_carro = [h3_tag.get_text(strip=True) for h3_tag in cartoes]
print(modelo_carro)

#Exportando em um DataFrame

import pandas as pd

df_modelos = pd.DataFrame(modelo_carro, columns=['Modelo de Carro'])
display(df_modelos.head())